YAN-14: Вёрстка страницы логина + логика авторизации.
ThunderbirdSecret/Game_Project pull request #10
Opened 2023-05-06 22:14 UTC by edword03

### Какую задачу решаем
- интегрировал eslint
- настроил аллиасы для коротких импортов
- сверстана страница авторизации и формы входа
- добавлен сервис входа и редирект после успешного запроса

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/57492283/236648343-aa623049-520e-4d4e-bc8b-a14322e4d3f2.png)

### TBD (если есть)

2023-05-06 23:09 UTC, ThunderbirdSecret requested changes
Хорошая типизация, продуманные решения в коде, круто что используешь classnames, при работа все таки командная. Раз мы потратили время на создание компонентов раннее, используй их, а не игнорируй. Проще расширять и делать лучше те компоненты, которые мы имеем, а не создавать заново похожие. Отдельное спасибо за алиасы, их не хватало

2023-05-06 23:09 UTC, ThunderbirdSecret commented on packages/client/src/components/ui/Button/Button.tsx
у нас же есть готовые кнопки, ты их сам ревьювил ```<Button styles={btnStyle.inputAttr}>Login</Button>```  В них уже содержались готовые миксины только размеры нужно проставить. Так что смердж с ветки components или dev эти компоненты и модифицируй, если считаешь нужным. А то какой смысл был тогда их делать?

2023-05-09 18:44 UTC, ThunderbirdSecret approved these changes

2023-05-11 08:43 UTC, kate-lozovaya requested changes

2023-05-11 08:43 UTC, kate-lozovaya commented on packages/client/src/components/ui/input/Input.tsx
> +        className={style.element}
[Исправление]
Не передал `id` в `input`, не будет связи с `label`
```suggestion
        id={id}
        className={style.element}
```

2023-05-11 08:43 UTC, kate-lozovaya commented on packages/client/src/components/ui/input/Input.tsx
> +        placeholder={props.placeholder}
[Предложение]
Если хочется явно указать `placeholder`, можно его тоже доставать из `props` заранее в строках 10 - 16, чтобы код был в одном стиле: `value={value}`, `placeholder={placeholder}`

2023-05-11 08:43 UTC, kate-lozovaya commented on packages/client/src/components/ui/Title/Title.tsx
> +	return <ComponentTag className={cn(styles.title, styles[tag], className)}>{children}</ComponentTag>;
[Вопрос]
Тут получается, что для всех заголовков по умолчанию вне зависимости от тега будет размер текста 40px? Точно ли это удобно?

2023-05-11 08:43 UTC, kate-lozovaya commented on packages/client/src/pages/auth/auth.tsx
> +    <div className={styles.container}>
[Предложение]
Может тут подойдет тег `main`?

2023-05-11 08:43 UTC, kate-lozovaya commented on packages/client/src/pages/auth/auth.tsx
> +            <div className={styles.formGroup}>
[Предложение]
Тут, вроде, можно обойтись без `div`, оставить два инпута, тогда для отступа между элементами, можно будет написать вот так:
```
.input + .input {
    margin-top: 20px;
}
```

2023-05-11 08:43 UTC, kate-lozovaya commented on packages/client/src/pages/auth/auth.tsx
> +          <p>or</p>
[Вопрос]
Мне кажется, что отступы очень крупные для такого небольшого текста. Так и задумано? 
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/25737137/ebfaefbd-df5d-4cc6-80d0-334c518c8976)

2023-05-11 08:45 UTC, kate-lozovaya commented
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )

И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.

2023-05-11 14:21 UTC, edword03 commented on packages/client/src/components/ui/Title/Title.tsx
> +	return <ComponentTag className={cn(styles.title, styles[tag], className)}>{children}</ComponentTag>;
У меня изначально была задумка сделать классы на каждый тег заголовка, и чтобы когда просто передаешь тот или иной тег применялись нужные стили, но не было обговоренно как должны выглядеть теги `h1-h6`

2023-05-11 14:22 UTC, edword03 commented on packages/client/src/pages/auth/auth.tsx
> +          <p>or</p>
Тут должна быть полоска разделяющая, но похоже после слияния с прошлым ПР удалили нужный цвет. Это поправлю

2023-05-11 14:30 UTC, edword03 commented on packages/client/src/pages/auth/auth.tsx
> +            <div className={styles.formGroup}>
А это мне кажется не будет работать, т.к класс инпут присваевается напрямую `<input />`, а сам компонент обернут дивом с лейблом, в который передается текст

2023-05-12 08:21 UTC, kate-lozovaya commented on packages/client/src/pages/auth/auth.tsx
> +            <div className={styles.formGroup}>
Да, в таком случае работать не будет

2023-05-12 08:26 UTC, kate-lozovaya approved these changes
Призывай после правок по ревью, чтобы в гитхабе было видно назначение

2023-05-12 09:20 UTC, merged