Yan 20
ThunderbirdSecret/Game_Project pull request #11
Opened 2023-05-16 17:06 UTC by mar-mar

### Какую задачу решаем
Вёрстка экрана игры Начало
Вёрстка экрана игры Завершение

### Скриншоты/видяшка (если есть)
исходный макет
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/12953732/0f739eb0-9a39-4698-a561-b88bed01f0c7)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/12953732/e1116aba-1d8c-4d49-94a0-7ce80172c1f3)
![Uploading image.png…]()

### TBD (если есть)

2023-05-16 18:55 UTC, ThunderbirdSecret approved these changes
Не совсем понимаю, что мы ждем от кнопки `resume`. А так на данном этапе все ок. Стили на  `Start` - очень круто сделаны

2023-05-17 08:01 UTC, mar-mar commented
> Не совсем понимаю, что мы ждем от кнопки `resume`. А так на данном этапе все ок. Стили на `Start` - очень круто сделаны

примерно такое гугл выдает на "game pause"
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/12953732/7c78a6f2-758f-4ef2-b3be-bfc2ee914f41)

2023-05-17 17:36 UTC, kate-lozovaya requested changes
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )

И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.


По ПР: 
в нескольких местах используются `transition` или `animation`, их лучше убирать в  `@media (prefers-reduced-motion: no-preference)`, чтобы анимация не включалась у пользователей, кто ее явно выключил. [Вот тут можно посмотреть](https://doka.guide/a11y/prefers-reduced-motion/) про этот медиа
и есть hover, его тоже лучше в медиа запрос убирать, чтобы на телефоне не было двойного клика на кнопку. Я обычно использовала `@media (hover: hover) and (pointer: fine)`, [в доке видела](https://doka.guide/css/hover/), что можно делать `@media (any-hover: hover)`
остальное написала комментами в ПР

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/components/ui/transparentButton/index.module.scss
> +*/
[Вопрос]
Этот комментарий еще нужен?

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/components/ui/transparentButton/TransparentButton.tsx
> +      <div className={cn(style.rootBack, backgroundClassName)} />
[Предложение]
Можно сделать фон через `::before` для `rootBody`, чтобы не создавать дополнительный `div`

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +  onChangeState: (gameState: GAME_STATES) => void
[Предложение]
Нравится оформление в TS для функций вот такое:
```suggestion
  onChangeState(gameState: GAME_STATES): void
```

Так они подсвечиваются другим цветом в ide, сразу видно, что функция, а что переменная

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +  const navigate = useNavigate()
[Исправление]
Нужно прогнать линтер и преттир, где-то есть `;`, где-то их нет.

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +    return newState
[Предложение]
Тут что-то неочевидное происходит.
Переход в следующее состояние однозначный, может создать объект, где ключи - состояние, а значения - следующие состояния?

```
const getNextState: Record<GAME_STATES, GAME_STATES> = {
  [GAME_STATES.Initialize]: GAME_STATES.Pause,
  ...
}
```

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +  }
[Предложение]
Можно переделать в объект. Попроще выглядит
```
const standbyText: Record< GAME_STATES , string> = {
  [GAME_STATES.Initialize]: 'Start...',
  [GAME_STATES.Paus]: 'Pause',
  ...
}
```

2023-05-17 17:36 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +    <div className={cn(styles.statdby, standbyClassName())}>
[Предложение]
Все получилось дивами. Может быть тут подойдет section?

2023-05-17 18:04 UTC, mar-mar commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +    return newState
Это тестовый вариант, только для того чтобы удобно смотреть версту

2023-05-17 18:23 UTC, mar-mar commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +  const navigate = useNavigate()
prettiter приходилось в ручном режиме использовать, так как его ранее не прогоняли
если бы прогнала, то были бы правки не по задаче
прогоню по всем, но оставлю только по своим файлам

2023-05-17 18:39 UTC, mar-mar commented on packages/client/src/components/ui/transparentButton/index.module.scss
> +*/
это - ой, убираю

2023-05-18 08:32 UTC, mar-mar commented on packages/client/src/components/ui/transparentButton/TransparentButton.tsx
> +      <div className={cn(style.rootBack, backgroundClassName)} />
Добавила, только через rootBody не получилось выставить zindex, получилось от root (пришлось ставить явные zindex для rootBody  и root::before, иначе кнопка вела себя по-разному в home и game (оказалось что влиял bacground-color у standby))

2023-05-18 08:33 UTC, mar-mar commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +  onChangeState: (gameState: GAME_STATES) => void
изменила, спасибо))

2023-05-18 08:34 UTC, mar-mar commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +  }
изменила, спасибо))

2023-05-18 08:36 UTC, mar-mar commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +    <div className={cn(styles.statdby, standbyClassName())}>
изменила, спасибо))

2023-05-18 10:56 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +    return newState
Поняла. Но в целом подход с объектом может быть удобным

2023-05-18 10:57 UTC, kate-lozovaya approved these changes

2023-05-18 10:57 UTC, kate-lozovaya commented on packages/client/src/pages/game/components/stanbdy/standby.tsx
> +    )
👍🏻

2023-05-18 10:57 UTC, kate-lozovaya commented on packages/client/src/pages/main/main.tsx
> +    <main className={style.root}>
👍🏻

2023-05-18 14:09 UTC, merged