Yan 16: Вёрстка страницы форума
ThunderbirdSecret/Game_Project pull request #16
Opened 2023-05-19 17:57 UTC by NikolayDimitriev

### Какую задачу решаем
- сверстана страница форума
- добавлены моковые данные для тем, сообщений и комментариев
- сделано модальное окно

### Скриншоты/видяшка (если есть)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/55017954/81a07835-aa18-4110-9f36-69834847b568)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/55017954/e22547a1-b361-49ec-af9f-f42a29339075)

### TBD (если есть)

2023-05-19 18:41 UTC, ThunderbirdSecret approved these changes
В общем и целом, все норм. Единственное замечание, взаимодействуй с командой, есть некоторые повторяющееся стили/типы/компоненты, не критично, но было бы быстрее и меньше повторяющегося кода

2023-05-19 18:41 UTC, ThunderbirdSecret commented on packages/client/src/mock/index.ts
> +export type TUser = {
Такой тип уже есть в файле api, нужно будет потом централизовать все типы в одном файле, чтобы избегать дубликатов. Но это скорее ко всей команде относится, не только к тебе

2023-05-19 18:41 UTC, ThunderbirdSecret commented on packages/client/src/components/forumForm/ForumForm.tsx
> +    <input
но у нас же есть готовый ипут, почему не пользуешься?

2023-05-19 21:19 UTC, NikolayDimitriev commented on packages/client/src/components/forumForm/ForumForm.tsx
> +    <input
Мне кажется готовый инпут, надо немного поправить, например, не отображать label, если не передели для него параметром, т.к. он занимает место. Еще некоторые стили перезаписываются

2023-05-21 19:24 UTC, kate-lozovaya requested changes
По формату комментов. Использую [Исправление], [Предложение], [Вопрос]
[Исправление] пишу там, где прям очень хочется увидеть исправление, но всегда можно все обсудить )

И хочется увидеть после ревью обработку каждого коммента от тебя. Можно писать текстом, можно ставить смайлики, резолвить мне удобнее самой, чтобы пройтись глазами, и посмотреть на код еще раз.

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/styles/index.module.scss
> +  overflow: hidden;
[Исправление]
Выглядит так, что свойства задублированы

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/mock/index.ts
> +export type TMessage = {
[Вопрос]
А почему типы в mock?
Моки же временные, они уйдут, когда будет апи

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/hooks/useModal.tsx
> +    setIsOpen(!isOpen)
[Исправление]
Когда новое значение стейта зависит от предыдущего, лучше записывать вот так:
```suggestion
    setIsOpen(prev => !prev)
```
Есть [вот такое на стековерфлоу](https://stackoverflow.com/questions/55495198/reacts-setstate-method-with-prevstate-argument)

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/topicList/TopicList.tsx
> +  openModal: () => void
[Предложение]
Мне нравится записывать тип функции вот так:
```suggestion
  openModal(): void
```
Так функции в ide часто подсвечиваются иначе, их проще отделить глазами от переменных

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/topic/Topic.tsx
> +      <ForumAvatar author={users.filter(u => u.id === topic.author_id)[0]} />
[Вопрос]
Сейчас `users` приходит из моков. 
А что будет потом? Может сразу передавать автора в пропсах?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/topic/Topic.module.scss
> +  margin-top: 30px;
[Предложение]
Не очень хорошо использовать марджин в самом компоненте, он становится менее универсальным, его наверняка не получится поставить к верху какого-нибудь контейнера. 
Лучше контролировать отступы из родителя

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/topic/Topic.module.scss
> +  width: 50px;
[Исправление]
Нужно добавить свойство `min-width: 50px;`. Если будет много текста, картинка сузится
<img width="200" alt="image" src="https://github.com/ThunderbirdSecret/Game_Project/assets/25737137/a394f805-7eab-41ac-a8ed-a5ea1a50fcbd">

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/topicList/TopicList.tsx
> +      <input placeholder="search" type="text" className={styles.searchInput} />
[Вопрос]
Цвет текста черный, кажется, должен быть белым. 
<img width="200" alt="image" src="https://github.com/ThunderbirdSecret/Game_Project/assets/25737137/cf54df46-6428-4ff5-ab8f-e0e765fd4647">

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/topicList/TopicList.tsx
> +  openModal,
[Предложение]
Тут в компоненте нет модального окна, непонятна связь с ним. Может лучше пропс назвать иначе? Как-нибудь связано с кликом и созданием новой темы

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/modal/Modal.tsx
> +        onClick={e => handleClick(e)}>
[Вопрос]
А почему клик тут, а не на крестике?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/modal/Modal.tsx
> +        onClick={e => handleClick(e)}>
Вообще вешать клики на `div` не очень хорошая практика, для этого есть кнопки. А если все же ставишь на `div`, нужно написать ему [роль](https://doka.guide/a11y/aria-roles/).

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/message/Message.tsx
> +  }, [message.user_id])
[Предложение]
Сейчас `users` - мок, как будешь получать его тут, когда будет `api`? Может передавать автора в пропсах?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/message/Message.tsx
> +        [styles.messageSupportAnswer]: author?.id === 1,
[Вопрос]
Это условие изменится позже? Может нужен флажок?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/message/Message.tsx
> +      <div className={styles.content}>{message.content}</div>
[Предложение]
Текст можно в тег `p` оборачивать вместо `div`

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/message/Message.module.scss
> +  width: 50px;
[Исправление]
Нужно добавить `min-width: 50px;`, иначе аватар будет сужаться при большом количестве текста рядом

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/comment/Comment.tsx
> +  }, [user_id])
[Предложение]
Писала в других местах про users, может тут тоже автора из пропсов брать?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/comment/Comment.module.scss
> +  width: 40px;
[Исправление]
В других файлах писала, что нужен `min-width`

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/comment/Comment.tsx
> +          <div className={styles.content} lang="ru">
[Предложение]
Лучше использовать тег p для текста

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/comment/Comment.tsx
> +          <div className={styles.content} lang="ru">
[Предложение]
Лучше использовать тег p для текста

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/commentsBlock/CommentsBlock.tsx
> +    setComments(selectedMessage.comments)
[Вопрос]
А почему бы не передать сразу все, что нужно в компонент, и не рассчитывать комментарии здесь?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/forumForm/ForumForm.module.scss
> +    position: absolute; /* Абсолютное позиционирование */
[Вопрос]
Комментарии тут нужны?

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/forumForm/ForumForm.tsx
> +    </Button>
[Исправление]
Картинка не по центру
<img width="78" alt="image" src="https://github.com/ThunderbirdSecret/Game_Project/assets/25737137/79d507bb-dc31-47a3-824a-841e28d84f90">

2023-05-21 19:24 UTC, kate-lozovaya commented on packages/client/src/components/messagesBlock/MessagesBlock.tsx
> +        <div className={styles.mainTheme}>Theme: {selectedTopic.theme}</div>
[Предложение]
Можно использовать тег p для текста

2023-05-22 11:03 UTC, NikolayDimitriev commented on packages/client/src/mock/index.ts
> +export type TMessage = {
вынес типы в отдельную папку models

2023-05-22 11:42 UTC, NikolayDimitriev commented on packages/client/src/components/topic/Topic.tsx
> +      <ForumAvatar author={users.filter(u => u.id === topic.author_id)[0]} />
Переделал моки. Будет каждый topic/message/comment хранить в себе автора

2023-05-22 11:47 UTC, NikolayDimitriev commented on packages/client/src/components/topic/Topic.module.scss
> +  margin-top: 30px;
Убрал margin, для родителя добавил gap

2023-05-22 11:50 UTC, NikolayDimitriev commented on packages/client/src/components/topic/Topic.module.scss
> +  width: 50px;
добавил flex-shrink: 0, а для текста "..." если текста больше чем на 2 строчки

2023-05-22 11:51 UTC, NikolayDimitriev commented on packages/client/src/components/topicList/TopicList.tsx
> +      <input placeholder="search" type="text" className={styles.searchInput} />
Исправил

2023-05-22 11:55 UTC, NikolayDimitriev commented on packages/client/src/components/message/Message.tsx
> +  }, [message.user_id])
Вынес в пропсы

2023-05-22 12:01 UTC, NikolayDimitriev commented on packages/client/src/components/message/Message.tsx
> +        [styles.messageSupportAnswer]: author?.id === 1,
думал выделять ответы от support, но сейчас переделал на окраску каждого второго

2023-05-22 12:18 UTC, NikolayDimitriev commented on packages/client/src/components/commentsBlock/CommentsBlock.tsx
> +    setComments(selectedMessage.comments)
переделал

2023-05-22 12:19 UTC, NikolayDimitriev commented on packages/client/src/components/forumForm/ForumForm.module.scss
> +    position: absolute; /* Абсолютное позиционирование */
Нет, удалил

2023-05-22 12:21 UTC, NikolayDimitriev commented on packages/client/src/components/forumForm/ForumForm.tsx
> +    </Button>
Исправил

2023-05-22 12:34 UTC, NikolayDimitriev commented on packages/client/src/components/modal/Modal.tsx
> +        onClick={e => handleClick(e)}>
Видимо когда делал, баганулось что-то. Не срабатывал клик на крестик, пришлось так делать

2023-05-22 12:34 UTC, NikolayDimitriev commented on packages/client/src/components/modal/Modal.tsx
> +        onClick={e => handleClick(e)}>
Исправил

2023-05-22 14:22 UTC, kate-lozovaya approved these changes

2023-05-22 14:22 UTC, kate-lozovaya commented on packages/client/src/components/ui/avatar-uploader/index.module.scss
> +  box-sizing: border-box;
[Предложение]
Вот такие правки лучше отдельным ПР делать, чтобы ревьювер не пропустил что-то важное

2023-05-22 14:22 UTC, kate-lozovaya commented on packages/client/src/components/modal/Modal.tsx
> +        <Button className={styles.closeButton} onClick={() => closeModal()}>
[Предложение]
Можно просто `onClick={closeModal}`, типы же одинаковые

2023-05-22 14:22 UTC, kate-lozovaya commented on packages/client/src/components/messagesBlock/MessagesBlock.tsx
> +            comment => comment.message_id === selectedMessage.id
[Предложение]
Может в `useMemo` положить вычисление?

2023-05-22 20:02 UTC, merged