add fullscreen Api
ThunderbirdSecret/Game_Project pull request #21
Opened 2023-05-22 15:10 UTC by ThunderbirdSecret

### Какую задачу решаем
Добавлено fullscreen API 

### Скриншоты/видяшка (если есть)

https://github.com/ThunderbirdSecret/Game_Project/assets/64640181/895ee7f1-8526-4c1f-b057-76d7e02ad5ec

### TBD (если есть)

2023-05-22 19:18 UTC, mar-mar reviewed
хорошая идея не показывать саму кнопку в полноэкранном режиме и не мучиться со сменой ее состояния
идеи хорошие - поправить реализацию

2023-05-22 19:18 UTC, mar-mar commented on packages/client/src/canvas/fullscreen.tsx
> +        canvas.exitFullscreen()
Ошибка: Ошибка в консоли Uncaught TypeError: l.exitFullscreen is not a function
document.exitFullscreen() - если хотим скинуть предыдущий, то надо поставить - до requestFullscreen

Предложение - типизировать props и ref ()
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/forward_and_create_ref/
(https://stackoverflow.com/questions/33796267/how-to-use-refs-in-react-with-typescript)

Предложение: убрать useState<string>(props.toggler), он ничего не меняет, сейчас всегда 'toggle on'

Предложение: По-хорошему, надо проверять canvas.requestFullscreen где-то заранее и "серить" или скрывать кнопку 

if (canvas) {
      if (canvas.requestFullscreen) 
заменить на 
if (canvas && canvas.requestFullscreen)      

Предложение: вместо canvas использовать обобщенное название типа domNode, так как fullScreen должно быть все равно элемент какого типа используется

2023-05-22 19:18 UTC, mar-mar commented on packages/client/src/canvas/fullscreen.tsx
> +      {title}
Предложение: переименовать title  = label и props.toggler тоже на props.label

2023-05-22 19:51 UTC, ThunderbirdSecret commented on packages/client/src/canvas/fullscreen.tsx
> +        canvas.exitFullscreen()
C типизацией беда в том что типы сanvas, и функции fullscreen между собой не дружат. По пропсам именно в том виде, в котором я ими пользуюсь, все рекомендуют использовать propTypes, или отключить правило на eslint, но я думаю это надо обговорить с командой, прежде, чем использовать.  Я пыталась ((

2023-05-22 20:26 UTC, mar-mar approved these changes

2023-05-23 14:33 UTC, kate-lozovaya requested changes

2023-05-23 14:33 UTC, kate-lozovaya commented on packages/client/src/canvas/canvas.tsx
> +  const label = 'toggle on'
[Предложение]
Можно вынести константу за компонент, чтобы она каждый раз не пересоздавалась

2023-05-23 14:33 UTC, kate-lozovaya commented on packages/client/src/canvas/fullscreen.tsx
> +export const Fullscreen = forwardRef(function Fullscreen(props: any, ref: any) {
[Вопрос]
А почему тут `any`?

2023-05-23 14:33 UTC, kate-lozovaya commented on packages/client/src/pages/game/game.tsx
> +    ctx.stroke()
[Предложение]
Может вынести в функцию?

2023-05-23 18:51 UTC, kate-lozovaya requested changes

2023-05-23 18:51 UTC, kate-lozovaya commented on packages/client/src/canvas/fullscreen.tsx
> +export const Fullscreen = forwardRef(function Fullscreen(props: any, ref: any) {
Вот [тут есть статья](https://dev.to/selbekk/forwarding-refs-in-typescript-elp), как использовать forwardRef с TS

2023-05-23 18:51 UTC, kate-lozovaya commented on packages/client/src/canvas/canvas.tsx
>  export const Canvas = (props: any) => {
[Исправление]
Для `props` тут тоже лучше тип прописать

2023-05-24 08:23 UTC, ThunderbirdSecret commented on packages/client/src/pages/game/game.tsx
> +    ctx.stroke()
Это уже по механике игры задача, она сейчас у другого человека в работе

2023-05-24 14:52 UTC, kate-lozovaya approved these changes

2023-05-24 15:55 UTC, merged