Yan 30: Hook/HOC для проверки авторизации
ThunderbirdSecret/Game_Project pull request #23
Opened 2023-05-22 20:48 UTC by NikolayDimitriev

### Какую задачу решаем
Авторизация проверяется через отдельно написанный HOC.
Роуты: game, forum, profile, leader board приватны если не авторизован
Роуты: login/register приватны, если уже авторизован

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-22 21:40 UTC, mar-mar reviewed
Код структурирован и хорошо читается, но есть недоработки в поведении

Ошибка - пользователь авторизирован, но показывает как будто не авторизирован
Как повторить - авторизоваться, а потом обновить страницу

Предложение - для удобства проверки вытащить (хотя бы) логин на заголовок

2023-05-22 21:40 UTC, mar-mar commented on packages/client/src/hoc/withAuth.tsx
> +    const redirectPath = options.onUnAuthPath
const redirectPath = isAuth ? options.onAuthPath : options.onUnAuthPath
Предложение: код можно сократить

2023-05-25 08:36 UTC, ThunderbirdSecret approved these changes

2023-05-26 18:50 UTC, kate-lozovaya requested changes
Посмотри, можно ли поправить циклическую зависимость. Нехорошо ее дизейблить

2023-05-26 18:50 UTC, kate-lozovaya commented on packages/client/src/store/store.ts
> +// eslint-disable-next-line import/no-cycle
[Вопрос]
Кажется, тут что-то неправильно сделано. Не должно быть циклической зависимости. Уверен, что хочешь просто ее задизейбить?

2023-05-26 18:50 UTC, kate-lozovaya commented on packages/client/src/hoc/withAuth.tsx
> +      if (pathname === ROUTES.AUTH || pathname === ROUTES.REGISTER) {
[Предложение]
Может вынести за пределы hoc в переменные, которые будет легко расширять при необходимости?

2023-05-26 18:50 UTC, kate-lozovaya commented on packages/client/src/hoc/withAuth.tsx
> +      pathname === ROUTES.LEADER_BOARD
[Предложение]
Может вынести за пределы hoc в переменные, которые будет легко расширять при необходимости?

2023-05-28 12:42 UTC, NikolayDimitriev commented on packages/client/src/hoc/withAuth.tsx
> +      if (pathname === ROUTES.AUTH || pathname === ROUTES.REGISTER) {
Вынес в отдельную функцию

2023-05-28 12:44 UTC, NikolayDimitriev commented on packages/client/src/store/store.ts
> +// eslint-disable-next-line import/no-cycle
Это пока что временное решение, потом разобьем actions отдельно на авторизацию и получение пользователя

2023-05-28 15:16 UTC, kate-lozovaya approved these changes

2023-05-28 15:39 UTC, merged