Yan 29 Service Workers
ThunderbirdSecret/Game_Project pull request #24
Opened 2023-05-27 08:56 UTC by mar-mar

### Какую задачу решаем
SW = service workers
Добавить Service Workers. Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета (не только элементы входа и пользовательские настройки, но и сама игра).

Проблемы - 
работает только в безопасном контексте - https и localhost
https - сейчас нет
поэтому надо разворачивать локально и проверять

Service Workers имеют свою стратегию кеширования, никак не реагируют на Cache-Control приложения
Если поставить точку остановки в Service Workers, то запросы уходят в бесконечное ожидание, поэтому добавлено логирование
Если отключить сеть на вкладке, все равно на сервер прилетает запрос sw.js (надо отключать сервер для проверки)
Проверять надо на порту сервера, а не на сервере отладки от vite  (там тоже включена работа с SW, но скорее всего надо вести два конфига для отладки и для прод и для отладки совсем выключать SW)
Если поставить галочку "Отключить кеш" в отладчике - то так же получаем проблему, что запросы уходят в бесконечное ожидание
Если я верно поняла при работе с SW, вкладку браузер переводит в автономный режим сам

### Скриншоты/видяшка (если есть)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/12953732/a311d397-62f0-42b5-8f59-fbf82a4e6d91)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/12953732/97d80fe4-76ef-463c-90ac-7785adf0b26f)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/12953732/71c3071d-9ef4-4ae7-a9dd-f8455a2ec3d3)
порт на скриншоте отладочный, будет тот который указан в server (const port = Number(process.env.SERVER_PORT) || 5001)
### TBD (если есть)

2023-05-27 16:36 UTC, ThunderbirdSecret approved these changes
Хорошо проделанная работа, отлично разобралась в достаточно сложной задаче. 👍🏻

2023-05-28 15:39 UTC, kate-lozovaya requested changes

2023-05-28 15:39 UTC, kate-lozovaya commented on packages/client/src/routes.ts
> +}
[Предложение]
Здесь можно избавиться от `as`, если вынести массив в переменную вот так:
```suggestion
export function isRoute(path: string) {
    const routes: string[] = [
        ROUTES.MAIN,
        ROUTES.GAME,
        ROUTES.FORUM,
        ROUTES.LEADER_BOARD,
        ROUTES.PROFILE,
        ROUTES.AUTH,
        ROUTES.REGISTER,
        ROUTES.ERROR_404,
        ROUTES.DOCUMENTAION,
    ];
    return routes.includes(path);
}
```

`as` просто выключает TS, лучше его не использовать, если это возможно

2023-05-28 15:39 UTC, kate-lozovaya commented on packages/server/index.ts
> +//createClientAndConnect()
[Вопрос]
Комментарии нужны?

2023-05-28 15:39 UTC, kate-lozovaya commented on packages/client/vite.config.ts
> +        // selfDestroying: true,
[Вопрос]
Комментарий нужен?

2023-05-28 15:39 UTC, kate-lozovaya commented on packages/client/src/sw.ts
> +// запретить logout, редактирование профиля в offline
[Вопрос]
А на это есть задачки в беклоге?

2023-05-28 16:59 UTC, mar-mar commented on packages/server/index.ts
> +//createClientAndConnect()
этот нужен, там идет заглушка для добавления работы с БД, она сейчас не работает нормально и все время ошибку выкидывает, решила закомментировать

2023-05-28 17:00 UTC, mar-mar commented on packages/client/vite.config.ts
> +        // selfDestroying: true,
оставляла специально, вики у нас нет, а этой настройкой можно удалить SW,
могу убрать

2023-05-28 17:11 UTC, mar-mar commented on packages/client/src/sw.ts
> +// запретить logout, редактирование профиля в offline
Создала общую задачу https://linear.app/yandex-game/issue/YAN-75/dorabotki-po-service-workers 
пометила Epic: no tag

2023-05-28 17:17 UTC, mar-mar commented on packages/client/src/routes.ts
> +}
исправила

2023-05-29 03:22 UTC, kate-lozovaya approved these changes

2023-05-29 19:41 UTC, merged