Yan-36: Добавить OAuth-авторизацию в проект.
ThunderbirdSecret/Game_Project pull request #27
Opened 2023-06-17 10:18 UTC by edword03

### Какую задачу решаем
Авторизация через сервис яндекса

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-17 14:21 UTC, ThunderbirdSecret approved these changes
Отдельное спасибо за хедер, придраться не к чему👍🏻

2023-06-18 18:36 UTC, mar-mar requested changes

2023-06-18 18:36 UTC, mar-mar commented on packages/client/src/store/service/service.action.ts
> +  'service/getServiceId',
Либо комментарии должны быть, либо надо не терять инфу в имени, что getServiceId это про oauth
Соседний код тоже надо поправить, service - это очень общее название

2023-06-18 18:36 UTC, mar-mar commented on packages/client/src/store/user/user.action.ts
> +      return (await userService.getUser()).data
тут либо не хватает try/catch,
либо надо отправлять fetchUser (если можно)

2023-06-18 18:36 UTC, mar-mar commented on packages/client/src/hoc/withAuth.tsx
> +          search.delete('code')
почему тут dispatch fetchUser, а в login не во вне (как тут) а внутри (user.action.ts)
и почему login ("старый") через событие, а тут прямой вызов апи

2023-06-18 18:36 UTC, mar-mar commented on packages/client/src/store/user/user.slice.ts
> +          state.error = action.payload as APIError
тут никак копи/паст не убрать?
тяжело читается и легко сделать ошибку при установке/использовании

2023-06-19 07:39 UTC, edword03 commented on packages/client/src/store/user/user.slice.ts
> +          state.error = action.payload as APIError
нет, никак

2023-06-19 07:45 UTC, edword03 commented on packages/client/src/store/service/service.action.ts
> +  'service/getServiceId',
Про сервис у меня изначально идея была, чтобы на служебные данные для приложения, id тот же для oauth, но т.к в эндпоинте само название такое, сделал так. Я поправлю конечно, чтобы было понятно, что конкретно oauth сервис

2023-06-19 07:47 UTC, edword03 commented on packages/client/src/store/user/user.action.ts
> +      return (await userService.getUser()).data
тут конкретно должно возвращаться значение пользователя в слайс, после логина возвращается только ответ с ок, поэтому приходится отдельно получать пользователя

2023-06-19 07:49 UTC, edword03 commented on packages/client/src/hoc/withAuth.tsx
> +          search.delete('code')
мне тут надо было, чтобы только в случае успешного ответа отправлять запрос на получение пользователя
а почему прямой вызов апи? потому что тут просто отправляется код от яндекса, чтобы в ответе получить аксес токен

2023-06-20 07:49 UTC, mar-mar approved these changes

2023-06-20 15:10 UTC, kate-lozovaya approved these changes

2023-06-21 17:59 UTC, merged