YAN 37: Добавить API для лидерборда
ThunderbirdSecret/Game_Project pull request #30
Opened 2023-06-26 15:12 UTC by NikolayDimitriev

### Какую задачу решаем
Сверстал страницу лидерборка
Добавил взаимодействие с API из [Swagger](https://ya-praktikum.tech/api/v2/swagger/#/Leaderboard/post_leaderboard__teamName_)
Добавил пагинацию и сортировку по 4 полям (логин, кол-во игр, последняя игра, кол-во очков)

### Скриншоты/видяшка (если есть)
![image](https://github.com/ThunderbirdSecret/Game_Project/assets/55017954/f2aa7c0a-2394-4fd5-b7fc-78fb82a5388b)

### TBD (если есть)

2023-06-26 16:26 UTC, ThunderbirdSecret approved these changes

2023-06-27 14:42 UTC, kate-lozovaya requested changes

2023-06-27 14:42 UTC, kate-lozovaya commented on packages/client/src/components/Select/Select.tsx
> +/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
[Вопрос]
Зачем включать правила, если потом из просто дизейблишь? Может пока они не нужны?

2023-06-27 14:42 UTC, kate-lozovaya commented on packages/client/src/components/Select/Select.tsx
> +  value: keyof Omit<TLeaderboardPlayerData, 'id'>
[Предложение]
Несколько раз повторяется тип `keyof Omit<TLeaderboardPlayerData, 'id'>`. Может вынести его в отдельный `type`?

2023-06-27 14:42 UTC, kate-lozovaya commented on packages/client/src/components/Select/Select.tsx
> +  const handleClick =
[Предложение]
Можно без этой функции обойтись, а сразу вызывать `onClick(value)`

2023-06-27 14:42 UTC, kate-lozovaya commented on packages/client/src/components/Select/Select.tsx
> +export const Select = (props: SelectProps) => {
[Предложение]
Лучше `OptionEl` вынести в отдельный файл. Если важна его связь с `Select`, то можно в папке `Select` сделать папку `Option`. Такие длинные и сложные файлы сложно читать

2023-06-28 20:37 UTC, NikolayDimitriev commented on packages/client/src/components/Select/Select.tsx
> +/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
Отключил)

2023-06-28 20:38 UTC, NikolayDimitriev commented on packages/client/src/components/Select/Select.tsx
> +  value: keyof Omit<TLeaderboardPlayerData, 'id'>
Вынес в отдельный `type`

2023-06-28 20:38 UTC, NikolayDimitriev commented on packages/client/src/components/Select/Select.tsx
> +  const handleClick =
Да, удалил лишнюю функцию

2023-06-28 20:39 UTC, NikolayDimitriev commented on packages/client/src/components/Select/Select.tsx
> +export const Select = (props: SelectProps) => {
Разбил на 2 компонента

2023-06-29 08:22 UTC, kate-lozovaya approved these changes

2023-06-29 10:07 UTC, merged